
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnqwfmoipuwgbplzowfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InducXdmbW9pcHV3Z2JwbHpvd2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzM2NDAsImV4cCI6MjA2MTY0OTY0MH0.0fxTmjUPphSl_PbBafkcW6ZBCFEmbpwTvAlkBUWoXVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
